allowBuilds:
  better-sqlite3: true
  electron-winstaller: true
  tesseract.js: true
  unrs-resolver: true
onlyBuiltDependencies:
  - "@napi-rs/canvas"
  - better-sqlite3
  - electron-winstaller
  - sharp
  - tesseract.js
  - unrs-resolver
